"""Turn the Vietnamese diagram scripts copied from report/tools into English ones (2026-09-30).
Every Vietnamese label is replaced by its English counterpart and the output goes to report/thesis-en/figures.
The Vietnamese scripts in report/tools and figures in report/thesis/figures are left untouched.
Run from report/tools-en: python translate_labels.py, then python h*_drawio.py, then export with draw.io."""
from pathlib import Path

HERE = Path(__file__).parent
T = {
 'h1_use_case_drawio.py': [
  ('Hệ thống PRISM', 'Person search system'), ('<i>Người dùng</i>', '<i>User</i>'),
  ('Quản trị viên<br>(Admin)', 'Administrator<br>(Admin)'), ('Giám sát viên<br>(Operator)', 'Operator'), ('Quản lý<br>(Viewer)', 'Viewer'),
  ('UC-01<br>Đăng nhập hệ thống', 'UC-01<br>Log in'), ('UC-15<br>Đăng xuất hệ thống', 'UC-15<br>Log out'),
  ('UC-02<br>Quản lý tài khoản<br>người dùng', 'UC-02<br>Manage user<br>accounts'), ('UC-03<br>Quản lý camera', 'UC-03<br>Manage cameras'),
  ('UC-04<br>Quản lý xử lý AI<br>trên camera', 'UC-04<br>Manage AI processing<br>of cameras'), ('UC-05<br>Cấu hình mô hình AI', 'UC-05<br>Configure AI models'),
  ('UC-06<br>Theo dõi trạng thái<br>hệ thống', 'UC-06<br>Monitor system<br>status'), ('UC-07<br>Kiểm tra hoạt động<br>của AI', 'UC-07<br>Check AI<br>operation'),
  ('UC-08<br>Xem nhật ký hệ thống', 'UC-08<br>View the audit log'),
  ('UC-09<br>Tìm kiếm người<br>bằng AI', 'UC-09<br>Search for people<br>with AI'), ('UC-10<br>Xem và đánh giá<br>kết quả tìm kiếm', 'UC-10<br>View and assess<br>search results'),
  ('UC-11<br>Quản lý hồ sơ<br>vụ việc', 'UC-11<br>Manage case<br>files'),
  ('UC-12<br>Xem thông tin<br>tổng quan', 'UC-12<br>View the<br>overview'), ('UC-13<br>Xem hồ sơ vụ việc', 'UC-13<br>View case files'),
  ('UC-14<br>Xem thông tin kết quả<br>tìm kiếm đã lưu', 'UC-14<br>View saved<br>search results'),
 ],
 'h2_architecture_drawio.py': [
  ("'Nguồn dữ liệu camera'", "'Camera data source'"), ("'7 tệp video<br>WILDTRACK'", "'7 WILDTRACK<br>video files'"),
  ("'7 camera<br>logic'", "'7 logical<br>cameras'"),
  ("'Tiến trình xử lý nền (AI worker)'", "'Background AI worker'"),
  ("'Bộ lập lịch phiên RTSP<br>(xoay vòng camera)'", "'RTSP session scheduler<br>(camera rotation)'"),
  ("'Hàng đợi công việc<br>(trong PostgreSQL)'", "'Job queue<br>(in PostgreSQL)'"),
  ("'Lấy mẫu khung hình (1/N)'", "'Frame sampling (1/N)'"),
  ("'Phát hiện người<br>YOLO11n'", "'Person detection<br>YOLO11n'"), ("'Theo vết<br>ByteTrack / BoT-SORT'", "'Tracking<br>ByteTrack / BoT-SORT'"),
  ("'<b>Bộ đệm track</b><br>track đang theo vết,<br>ứng viên khung hình đại diện'", "'<b>Track buffer</b><br>tracks being followed,<br>representative frame candidates'"),
  ("'Mã hóa ảnh<br>RaSa'", "'Image encoder<br>RaSa'"), ("'Ghi dữ liệu lần xuất hiện<br>(PENDING → READY)'", "'Write appearance data<br>(PENDING → READY)'"),
  ("'Người dùng'", "'Users'"), ("'Quản trị viên'", "'Administrator'"), ("'Giám sát viên'", "'Operator'"), ("'Quản lý'", "'Viewer'"),
  ("'Ứng dụng web (React)'", "'Web application (React)'"), ("'Tệp video tải lên'", "'Uploaded video file'"),
  ("'Máy chủ ứng dụng (Flask API)'", "'Application server (Flask API)'"),
  ("'<i>xác thực, phân quyền, tìm kiếm,<br>vụ việc, quản trị</i>'", "'<i>authentication, access control, search,<br>cases, administration</i>'"),
  ("'Kiểm tra truy vấn,<br>xác định phạm vi'", "'Validate query,<br>determine scope'"),
  ("'Tạo câu mô tả<br>từ thuộc tính'", "'Build a sentence<br>from attributes'"),
  ("'Mã hóa truy vấn<br>RaSa ảnh / văn bản'", "'Query encoder<br>RaSa image / text'"),
  ("'Tầng lưu trữ'", "'Storage layer'"),
  ("'<b>PostgreSQL</b><br>tài khoản, camera, lần xuất hiện,<br>vụ việc, nhật ký, hàng đợi'", "'<b>PostgreSQL</b><br>accounts, cameras, appearances,<br>cases, audit log, job queue'"),
  ("'<b>Milvus</b> (vector)<br>vector 256 chiều + khu vực,<br>camera, thời gian'", "'<b>Milvus</b> (vectors)<br>256-d vectors + area,<br>camera, time'"),
  ("'<b>MinIO</b><br>khung hình đại diện<br>(bucket riêng tư)'", "'<b>MinIO</b><br>representative frames<br>(private bucket)'"),
  ("'công việc kế tiếp'", "'next job'"), ("'từng khung hình đã lấy mẫu'", "'each sampled frame'"),
  ("'khung bao người'", "'person boxes'"), ("'cập nhật track'", "'update tracks'"),
  ("'hết phiên hoặc hết tệp:<br>ảnh người (cắt tạm)'", "'end of session or file:<br>person crop (temporary)'"),
  ("'vector đặc trưng'", "'feature vector'"), ("'tạo công việc<br>(tệp tải lên)'", "'create job<br>(uploaded file)'"),
  ("'tệp video<br>lưu tạm'", "'staged<br>video file'"), ("'truy vấn'", "'query'"), ("'thuộc tính'", "'attributes'"),
  ("'ảnh, câu mô tả'", "'image, sentence'"), ("'kết quả'", "'results'"), ("'tải lên'", "'upload'"),
  ("'câu tiếng Anh'", "'English sentence'"), ("'quyền, thông tin mô tả'", "'permissions, descriptions'"),
  ("'vector truy vấn<br>(lọc trước)'", "'query vector<br>(pre-filtered)'"), ("'kết quả<br>gần nhất'", "'nearest<br>results'"),
  ("'khung hình'", "'frames'"), ('H2 - Kiến trúc', 'H2 - Architecture'),
 ],
 'h3_pipeline_flow_drawio.py': [
  ("'Công việc xử lý<br>(camera, nguồn, N)'", "'Processing job<br>(camera, source, N)'"),
  ("'Đọc, giải mã khung hình kế tiếp'", "'Read and decode the next frame'"),
  ("'Hết nguồn hoặc<br>đủ số khung của phiên?'", "'End of source or<br>session frame count reached?'"),
  ("'Phát hiện người<br>(YOLO11n)'", "'Person detection<br>(YOLO11n)'"), ("'Khung bao người'", "'Person boxes'"),
  ("'Theo vết<br>(ByteTrack /<br>BoT-SORT)'", "'Tracking<br>(ByteTrack /<br>BoT-SORT)'"),
  ("'Cập nhật ứng viên khung<br>hình đại diện (tối đa 3);<br>lần xuất hiện kết thúc:<br>chọn và giữ khung hình đại diện'",
   "'Update representative frame<br>candidates (at most 3);<br>appearance ended:<br>choose and keep its frame'"),
  ("'Kết thúc các lần xuất hiện<br>còn đang theo vết'", "'End the appearances<br>still being tracked'"),
  ("'Với mỗi lần xuất hiện: cắt tạm<br>vùng người (nới 5%)'", "'For each appearance: crop the<br>person temporarily (widen 5%)'"),
  ("'Mã hóa ảnh<br>(RaSa)'", "'Image encoder<br>(RaSa)'"),
  ("'Vector 256 chiều, khung hình,<br>khung bao'", "'256-d vector, frame,<br>bounding box'"),
  ("'Ghi từng lần xuất hiện vào ba kho<br>(PENDING → READY, thử lại)'", "'Write each appearance to three stores<br>(PENDING → READY, retries)'"),
  ("'Kết thúc công việc'", "'End of job'"),
  ("'<b>PostgreSQL</b><br>thông tin mô tả'", "'<b>PostgreSQL</b><br>descriptions'"),
  ("'<b>MinIO</b><br>khung hình'", "'<b>MinIO</b><br>frames'"),
  ("'Có'", "'Yes'"), ("'Không'", "'No'"), ('H3 - Lưu đồ xử lý camera', 'H3 - Job flowchart'),
 ],
 'h4_search_sequence_drawio.py': [
  ("'Giám sát viên'", "'Operator'"), ("'Ứng dụng web'", "'Web application'"), ("'Máy chủ<br>ứng dụng'", "'Application<br>server'"),
  ("'nhập truy vấn'", "'enter query'"), ("'gửi truy vấn, bộ lọc, k'", "'send query, filters, k'"),
  ("'kiểm tra phiên, khu vực'", "'check session, area'"), ("'camera đang vận hành'", "'operational cameras'"),
  ("'tạo câu tiếng Anh<br>(nếu theo thuộc tính)'", "'build English sentence<br>(attribute search)'"),
  ("'mã hóa truy vấn'", "'encode query'"),
  ("'[thiếu kết quả hợp lệ;<br>k nhân đôi, tối đa 3 lượt]'", "'[valid results missing;<br>k doubled, at most 3 rounds]'"),
  ("'tìm k vector gần nhất (lọc trước)'", "'find k nearest vectors (pre-filtered)'"),
  ("'mã lần xuất hiện + điểm'", "'appearance ids + scores'"), ("'đối chiếu, kiểm tra'", "'cross-check'"),
  ("'camera, thời điểm, bbox'", "'camera, time, bbox'"), ("'tối đa k kết quả'", "'at most k results'"),
  ("'[mỗi kết quả]'", "'[each result]'"), ("'yêu cầu ảnh người'", "'request person image'"),
  ("'kiểm tra quyền'", "'check permission'"), ("'đọc khung hình đại diện'", "'read representative frame'"),
  ("'khung hình toàn cảnh'", "'full frame'"), ("'cắt, nới khung,<br>làm tối xung quanh'", "'crop, widen,<br>dim surroundings'"),
  ("'ảnh người'", "'person image'"), ("'hiển thị'", "'display'"), ('H4 - Tuần tự tìm kiếm', 'H4 - Search sequence'),
 ],
 'h5_case_sequence_drawio.py': [
  ("'Giám sát viên'", "'Operator'"), ("'Ứng dụng web'", "'Web application'"), ("'Máy chủ ứng dụng'", "'Application server'"),
  ("'chọn kết quả để lưu'", "'choose a result to save'"), ("'[tạo vụ việc mới]'", "'[create a new case]'"),
  ("'tạo vụ việc (tiêu đề, ghi chú,<br>mã lần xuất hiện)'", "'create case (title, notes,<br>appearance id)'"),
  ("'tạo vụ việc, người phụ trách<br>lấy từ phiên đăng nhập'", "'create case, owner taken<br>from the login session'"),
  ("'[thêm vào vụ việc đã có]'", "'[add to an existing case]'"),
  ("'thêm kết quả (mã vụ việc,<br>mã lần xuất hiện)'", "'add result (case id,<br>appearance id)'"),
  ("'kiểm tra vụ việc của mình,<br>đang xử lý'", "'check the case is owned<br>and open'"),
  ("'kiểm tra lần xuất hiện: sẵn sàng,<br>camera vận hành, đúng khu vực'", "'check appearance: ready,<br>camera operational, right area'"),
  ("'tạo mục kết quả + bản chụp,<br>ghi nhật ký'", "'create result entry + snapshot,<br>write audit log'"),
  ("'vụ việc, số phiên bản'", "'case, version number'"),
  ("'[đánh dấu hoàn thành khi lưu]'", "'[close the case when saving]'"),
  ("'đổi trạng thái Hoàn thành<br>(kèm số phiên bản)'", "'set status Closed<br>(with version number)'"),
  ("'so số phiên bản, cập nhật,<br>ghi nhật ký'", "'compare version, update,<br>write audit log'"),
  ("'thành công / lỗi'", "'success / error'"), ("'thông báo kết quả'", "'report the outcome'"),
  ('H5 - Tuần tự vụ việc', 'H5 - Case sequence'),
 ],
 'h6_track_state_drawio.py': [
  ("'<b>Chờ</b><br>(PENDING)'", "'<b>Pending</b><br>(PENDING)'"), ("'<b>Sẵn sàng</b><br>(READY)'", "'<b>Ready</b><br>(READY)'"),
  ("'<b>Thất bại</b><br>(FAILED)'", "'<b>Failed</b><br>(FAILED)'"),
  ("'ghi bản ghi + sự kiện<br>outbox (một giao dịch)'", "'write record + outbox<br>event (one transaction)'"),
  ("'đã ghi khung hình (MinIO)<br>và vector (Milvus)'", "'frame (MinIO) and<br>vector (Milvus) written'"),
  ("'lỗi tạm thời /<br>hẹn thử lại'", "'transient error /<br>retry scheduled'"),
  ("'lỗi không phục hồi<br>hoặc hết 5 lần thử'", "'unrecoverable error<br>or 5 attempts used'"),
  ("'đưa lại hàng chờ<br>(requeue-track)'", "'requeue<br>(requeue-track)'"),
  ("'đối soát phát hiện thiếu<br>khung hình, vector<br>hoặc sai mã băm'", "'reconciliation finds a<br>missing frame or vector,<br>or a wrong hash'"),
  ('H6 - Trạng thái lần xuất hiện', 'H6 - Appearance states'),
 ],
 'h7_job_state_drawio.py': [
  ("'<b>Chờ xử lý</b><br>(PENDING)'", "'<b>Queued</b><br>(PENDING)'"), ("'<b>Đang xử lý</b><br>(RUNNING)'", "'<b>Running</b><br>(RUNNING)'"),
  ("'<b>Đã hủy</b><br>(CANCELLED)'", "'<b>Cancelled</b><br>(CANCELLED)'"), ("'<b>Thất bại</b><br>(FAILED)'", "'<b>Failed</b><br>(FAILED)'"),
  ("'<b>Hoàn thành</b><br>(SUCCEEDED)'", "'<b>Succeeded</b><br>(SUCCEEDED)'"),
  ("'Quản trị viên tải tệp lên /<br>bộ lập lịch tạo phiên RTSP'", "'Administrator uploads a file /<br>scheduler creates an RTSP session'"),
  ("'tiến trình xử lý nền<br>nhận việc (giữ chỗ 60 s)'", "'background worker<br>claims it (60 s lease)'"),
  ("'báo hiệu định kỳ / gia hạn giữ chỗ;<br>lỗi tạm thời, còn lượt thử / chờ rồi thử lại;<br>hết hạn giữ chỗ / nhận lại'",
   "'heartbeat / lease renewed;<br>transient error, attempts left / wait and retry;<br>lease expired / claimed again'"),
  ("'xử lý xong'", "'processing done'"),
  ("'lỗi không phục hồi<br>hoặc hết số lần thử'", "'unrecoverable error<br>or attempts exhausted'"),
  ("'yêu cầu hủy, camera ngừng<br>vận hành hoặc tắt AI'", "'cancel request, camera<br>retired or AI disabled'"),
  ("'yêu cầu hủy'", "'cancel request'"), ('H7 - Trạng thái công việc', 'H7 - Job states'),
 ],
 'h12_screen_flow_drawio.py': [
  ("'Đăng nhập'", "'Login'"), ("'Quản trị viên'", "'Administrator'"), ("'Quản trị'", "'Administration'"),
  ("['Tài khoản', 'Camera', 'Xử lý AI', 'Mô hình AI', 'Xử lý video']", "['Accounts', 'Cameras', 'AI processing', 'AI models', 'Video processing']"),
  ("'Giám sát'", "'Monitoring'"),
  ("['Trạng thái hệ thống', 'Kiểm tra AI', 'Nhật ký hệ thống']", "['System status', 'AI check', 'Audit log']"),
  ("'Giám sát viên'", "'Operator'"), ("'Tìm kiếm người'", "'Person search'"),
  ("'Chi tiết kết quả<br>(khung hình toàn cảnh)'", "'Result details<br>(full frame)'"),
  ("'Tạo vụ việc mới /<br>Thêm vào vụ việc đã có'", "'Create new case /<br>Add to existing case'"),
  ("'Vụ việc của tôi<br>(danh sách + chi tiết)'", "'My cases<br>(list + details)'"),
  ("'Quản lý'", "'Viewer'"), ("'Tổng quan'", "'Overview'"),
  ("'Hồ sơ vụ việc<br>(danh sách + chi tiết)'", "'Case files<br>(list + details)'"),
  ("'chọn kết quả'", "'select result'"), ("'lưu kết quả'", "'save result'"),
  ("'chọn kết quả<br>đã lưu'", "'select saved<br>result'"), ("'tìm kiếm'", "'search'"),
  ("'chọn vụ việc gần đây'", "'select a recent case'"), ('H12 - Luồng màn hình', 'H12 - Screen flow'),
 ],
}

for name, pairs in T.items():
    p = HERE / name
    s = p.read_text(encoding='utf-8')
    s = s.replace('/report/thesis/figures/', '/report/thesis-en/figures/')
    missing = [a for a, _ in pairs if a not in s]
    for a, b in pairs:
        s = s.replace(a, b)
    p.write_text(s, encoding='utf-8')
    print(name, 'missing:', missing)
